server:
  port: 8669

grpc:
  port: 8670

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zpflow

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: